os: osx
dist: trusty
language: generic

sudo: false

before_install:
 - brew update
 - brew install python3
 - pip3 install numpy

matrix:
  include:
    - install: travis_wait 50 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3 --without-numpy
      env:
        - version=HEAD HOMEBREW_DEVELOPER=1
    - install: travis_wait 50 brew install ./Formula/rdkit.rb --build-from-source --with-python3 --without-numpy
      env:
        - version=current HOMEBREW_DEVELOPER=1
